site_name: Comm 2206
theme: material

repo_name: 'erilot/2206-mkdocs'
repo_url: 'https://github.com/erilot/2206-mkdocs'

markdown_extensions:
  - admonition
  - codehilite

extra:
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Open Sans'
    code: 'Source Code Pro'
  feature:
    tabs: true

pages:
  - "Course Information":
    - Assignments: course/assignments.md
    - Lab 1: course/lab1.md
    - Lab 2: course/lab2.md
    - Lab 3: course/lab3.md
    - Lab 4: course/lab4.md
    - Lab 5: course/lab5.md
    - Lab 6: course/lab6.md
    - Lab 7: course/lab7.md
    - Lab 8: course/lab8.md
    - Lab 9: course/lab9.md
  - "MkDocs":
    - Home: mkdocs-intro/index.md
    - About MkDocs: mkdocs-intro/about-mkdocs.md
    - References: mkdocs-intro/mkdocs-references.md
    - A Simple MkDocs Project: mkdocs-intro/simple-project.md
    - Installing the Toolset: mkdocs-intro/installing.md
    - Using MkDocs: mkdocs-intro/using.md
    - Command Line Reference: mkdocs-intro/cmd-reference.md
    - Markdown Reference: mkdocs-intro/md-reference.md
  - "APIs":
    - About APIs: apis/about-apis.md
    - Assignment: apis/assignment.md
