site_name: Comm 2206
theme: 
  name: material
  feature:
    tabs: true

repo_name: 'erilot/2206-mkdocs'
repo_url: 'https://github.com/erilot/2206-mkdocs'

markdown_extensions:
  - admonition
  - codehilite

extra:
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Open Sans'
    code: 'Source Code Pro'

    
pages:
  - "Home": index.md
  - "Course":
    - Outline: course/outline.md
    - Assignments: course/assignments.md
  - "Components":
    - Labs:
      - Lab 1: course/labs/lab1.md
    - Project:
      - Project Overview: course/project/project-overview.md
      - Project Detail: course/project/project-detail.md
  # - "Markdown":
  #   - Reference : markdown/md-reference.md
